config/routes.rb
Rails.application.routes.draw do
  scope :sidedoor do
    scope controller: :admins do
      root action: :enter, as: :enter_sidedoor
      post "", action: :unlock
      get :leave, action: :leave, as: :leave_sidedoor
    end

    resources :admins, except: [:show, :destroy]
    get "admins/init", controller: :admins, action: :init, as: :init_admin
    get "admins/:id/delete", controller: :admins, action: :destroy, as: :delete_admin

    resources :projects, only: [:index, :new, :edit, :create, :update]
    scope :projects, controller: :projects do
      get "/batch", action: :batch, as: :batch_projects
      post "/batch", action: :batch_update, as: :batch_update_projects
      get ":id", action: :index
      get ":id/preview", action: :show, as: :show_project
      get ":id/delete", action: :destroy, as: :delete_project
      get ":id/recall", action: :recall, as: :recall_project
    end

    resources :headlines, only: [:index, :new, :edit, :create, :update]
    scope :headlines, controller: :headlines do
      post "sort", action: :sort, as: :sort_headline
      get ":id/delete", action: :destroy, as: :delete_headline
      get "api/:id", action: :api, as: "headlines_api"
    end

    scope :sticky, controller: :stickies do
      root action: :edit, as: :sticky
      post "", action: :update
    end

    scope :contacts, controller: :contacts do
      root action: :index, as: "contacts"
      get "contacts/:id", action: :show, as: "contact"
      get "contacts/:id/resend", action: :resend, as: "resend_contact"
      get "contacts/:id/delete", action: :destroy, as: "delete_contact"
    end

    scope :preference, controller: :preferences do
      root action: :edit, as: :preference
      patch "", action: :update
    end

    get "help/:show", controller: :sidedoor, action: :help_api, as: "help_api"
  end

  root action: :show, controller: "published_projects"
  get "locale/:locale", action: :locale, controller: "published_projects", as: "locale"
  get ":page", action: :show, controller: "published_projects", as: "publish"
  post "contact", action: :contact, controller: "published_projects", as: "send"
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
  <div class="error-block">
    <h2><%= pluralize(admin.errors.count, "件のエラーがあります") %></h2>
      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="island">
    <%= form.label :name, class: "dew-text-label" %>
    <%= form.text_field :name, class: "dew-text" %>
    <%= form.label :email, class: "dew-text-label" %>
    <%= form.text_field :email, class: "dew-text" %>

    <div>
      <div class="mdc-form-field">
        <div class="mdc-checkbox">
          <%= form.check_box :sendmail, class: "mdc-checkbox__native-control" %>
          <div class="mdc-checkbox__background">
            <svg class="mdc-checkbox__checkmark" viewBox="0 0 24 24">
              <path class="mdc-checkbox__checkmark-path" fill="none" stroke="white" d="M1.73,12.91 8.1,19.28 22.79,4.59"></path>
            </svg>
            <div class="mdc-checkbox__mixedmark"></div>
          </div>
        </div>
        <%= form.label :sendmail, "受信メッセージをメールアドレスに転送する" %>
      </div>
    </div>

    <%= form.label :password, class: "dew-text-label" %>
    <%= form.password_field :password, class: "dew-text" %>
    <%= form.label :password_confirmation, class: "dew-text-label" %>
    <%= form.password_field :password_confirmation, class: "dew-text" %>
    <hr>
    <div class="mdc-form-field">
      <div class="mdc-radio mdc-ripple-upgraded mdc-ripple-upgraded--unbounded">
        <%= form.radio_button :level, "root", class: "mdc-radio__native-control", disabled: !controller.root? %>
        <div class="mdc-radio__background">
          <div class="mdc-radio__outer-circle"></div>
          <div class="mdc-radio__inner-circle"></div>
        </div>
      </div>
      <%= form.label :level, "システム管理者" %>
    </div>
    <div class="mdc-form-field">
      <div class="mdc-radio mdc-ripple-upgraded mdc-ripple-upgraded--unbounded">
        <%= form.radio_button :level, "owner", class: "mdc-radio__native-control", disabled: !controller.root? %>
        <div class="mdc-radio__background">
          <div class="mdc-radio__outer-circle"></div>
          <div class="mdc-radio__inner-circle"></div>
        </div>
      </div>
      <%= form.label :level, "サイトオーナー" %>
    </div>
    <div class="mdc-form-field">
      <div class="mdc-radio mdc-ripple-upgraded mdc-ripple-upgraded--unbounded">
        <%= form.radio_button :level, "contributor", class: "mdc-radio__native-control", disabled: !controller.root? %>
        <div class="mdc-radio__background">
          <div class="mdc-radio__outer-circle"></div>
          <div class="mdc-radio__inner-circle"></div>
        </div>
      </div>
      <%= form.label :level, "編集のみ" %>
    </div>
  </div>
  <%= form.button "Save", class: "mdc-fab mdc-fab--extended mdc-ripple-upgraded" %>
  <% if controller.root? %>
  <%= link_to button_tag("Back", type: "button", class: "mdc-fab mdc-fab--extended mdc-ripple-upgraded"), admins_path %>
  <% end %>
<% end %>

app/views/admins/edit.html.erb
<h1>管理ユーザー編集</h1>

<%= render 'form', admin: @admin %>

app/views/admins/enter.html.erb
<style>
  html, body, .entry-plate, .enter-main {
    height: 100%;
  }
  .enter-main {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    background: linear-gradient(170deg, #edf2e8, #ccccbb);
    box-sizing: border-box;
  }
  .enter-area {
    width: 300px;
    text-align: center;
    padding: 30px;
  }
  .enter-input {
    font-family: "Iowan Old Style", "游明朝体", "Yu Mincho", YuMincho, "ヒラギノ明朝 Pro", "Hiragino Mincho Pro", "MS P明朝", "MS PMincho", serif;
    font-weight: 500;
    letter-spacing: 1px;
    padding: 10px 20px 12px;
    border: 1px solid #cccccc;
    border-radius: 18px;
    margin: 4%;
  }
  .enter-submit {
    font-family: 'Material Icons';
    font-size: 5rem;
    cursor: pointer;
    background: none;
    padding: 10px 20px 10px 17px;
    border: none;
    color: #ffffff;
    text-shadow: 0 1px 10px #ffffff;
    transition: text-shadow 0.5s;
  }
  .enter-submit:hover {
    text-shadow: 0 1px 18px #ffffff;
  }
  .enter-submit:active {
    color: #444455;
  }
</style>

<%= form_for :admin, url: enter_sidedoor_path, html: {class: "entry-plate"} do |f| %>
<main class="enter-main">
  <div class="enter-area">
    <div><%= f.text_field :name, class: "enter-input", placeholder: "name" %></div>
    <div><%= f.password_field :password, class: "enter-input", placeholder: "password" %></div>
    <div><%= f.submit 'vpn_key', class: "enter-submit" %></div>
    <p><%= notice %></p>
  </div>
</main>
<% end %>

app/views/admins/index.html.erb
<h1>管理ユーザー編集</h1>

<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <% @admins.each do |admin| %>
    <div class="mdc-card mdc-layout-grid__cell mdc-layout-grid__cell--span-3">
      <%= link_to edit_admin_path(admin) do %>
      <div class="mdc-card__primary-action mdc-ripple-upgraded">
        <div class="card-surface">
          <h2 class="mdc-typography--headline6">
            <% if admin.level == "root" %>
              <i class="material-icons">account_balance</i>
            <% elsif admin.level == "owner" %>
              <i class="material-icons">bookmark</i>
            <% end %>
            <%= admin.name %>
          </h2>
          <h3 class="mdc-typography--subtitle2">
            <%= admin.email %>
            <% if admin.sendmail %>&#10003;<% end %>
          </h3>
          <% if admin.id == @current_admin.id %>
          <div class="card-supplement">Loged In</div>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="mdc-card__actions">
        <div class="mdc-card__action-icons">
          <%= link_to edit_admin_path(admin) do %>
          <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">settings<p class="button-label">編集</p></button>
          <% end %>
          <%= link_to delete_admin_path(admin) do %>
          <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">delete<p class="button-label">削除</p></button>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="mdc-card mdc-layout-grid__cell mdc-layout-grid__cell--span-3 card-new">
      <div class="mdc-card__primary-action mdc-ripple-upgraded">
        <div class="card-surface">
          <%= link_to new_admin_path do %>
          <i class="material-icons">add</i>
          <h2>Create New User</h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<h1>管理ユーザー登録</h1>

<%= render 'form', admin: @admin %>