config/routes.rb
Rails.application.routes.draw do
  scope :sidedoor do
    scope controller: :admins do
      root action: :enter, as: :enter_sidedoor
      post "", action: :unlock
      get :leave, action: :leave, as: :leave_sidedoor
    end

    resources :admins, except: [:show, :destroy]
    get "admins/init", controller: :admins, action: :init, as: :init_admin
    get "admins/:id/delete", controller: :admins, action: :destroy, as: :delete_admin

    resources :projects, only: [:index, :new, :edit, :create, :update]
    scope :projects, controller: :projects do
      get "/batch", action: :batch, as: :batch_projects
      post "/batch", action: :batch_update, as: :batch_update_projects
      get ":id", action: :index
      get ":id/preview", action: :show, as: :show_project
      get ":id/delete", action: :destroy, as: :delete_project
      get ":id/recall", action: :recall, as: :recall_project
    end

    resources :headlines, only: [:index, :new, :edit, :create, :update]
    scope :headlines, controller: :headlines do
      post "sort", action: :sort, as: :sort_headline
      get ":id/delete", action: :destroy, as: :delete_headline
      get "api/:id", action: :api, as: "headlines_api"
    end

    scope :sticky, controller: :stickies do
      root action: :edit, as: :sticky
      post "", action: :update
    end

    scope :contacts, controller: :contacts do
      root action: :index, as: "contacts"
      get "contacts/:id", action: :show, as: "contact"
      get "contacts/:id/resend", action: :resend, as: "resend_contact"
      get "contacts/:id/delete", action: :destroy, as: "delete_contact"
    end

    scope :preference, controller: :preferences do
      root action: :edit, as: :preference
      patch "", action: :update
    end

    get "help/:show", controller: :sidedoor, action: :help_api, as: "help_api"
  end

  root action: :show, controller: "published_projects"
  get "locale/:locale", action: :locale, controller: "published_projects", as: "locale"
  get ":page", action: :show, controller: "published_projects", as: "publish"
  post "contact", action: :contact, controller: "published_projects", as: "send"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  has_many :blocks, dependent: :destroy
  accepts_nested_attributes_for :blocks, allow_destroy: true
  has_many :roles, dependent: :destroy
  accepts_nested_attributes_for :roles, allow_destroy: true
  attr_accessor :file
  mount_uploader :file, ImageUploader
  has_one :published_project, foreign_key: "id"

  before_validation :parse_save
  validates :title, presence: true
  validates :date, presence: true

  before_destroy :destroy_with_published
  after_destroy :file_remove

  private

  def parse_save
    # 背景色なしならtransparentに
    self.color_bg ||= "transparent"
    self.color_edge ||= "transparent"

    # overviewを登録
    en = []
    jp = []
    blocks.find_all { |b| b.type == "text" }.sort_by(&:display_id).each do |block|
      en << block.text_en.presence
      jp << block.text_jp.presence
    end
    self.overview_en = en.compact.join(" ").truncate(200)
    self.overview_jp = jp.compact.join(" ").truncate(100).presence || overview_en
  end

  def destroy_with_published
    PublishedProject.find(id).destroy if PublishedProject.exists?(id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < SidedoorController
  layout "sidedoor"
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.includes(:category, published_project: [:page]).order("published_projects.id IS NULL DESC", "pages.order DESC", date: :desc)
    @index = Page.project_source_index
  end

  def show
    @page_no = 0
    @project = Project.find_by_id(params[:id])
    @blocks = @project.blocks
    @roles = @project.roles
    @meta_title = "[Preview] " + @project.title
    flash.now[:notice] = "Preview Mode"
    render template: "published_projects/show", layout: "portfolio"
  end

  def new
    @preference = Preference.last
    @project = Project.new(
      category_id: 1,
      color_txt: '#000000',
      color_bg: "transparent",
      color_edge: @preference.default_color_edge,
      date: Date.today,
      is_visible: true
    )
    @blocks = []
    @roles = []
    set_props
    render "edit"
  end

  def edit
    @project = Project.find(params[:id])
    @blocks = @project.blocks.order(:display_id)
    @roles = @project.roles.order(:display_id)
    @is_issued = PublishedProject.exists?(params[:id])
    @meta_title = @project.title
    set_props

    @file_size = @project.file.size
    @blocks.each do |block|
      @file_size += block.file.size
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      if params[:button] == "issue"
        if publish_project
          redirect_to projects_path, notice: "#{@project.title}を公開しました"
        else
          set_cache
          flash.now[:notice] = "公開に失敗しました"
          render :edit
        end
      else
        redirect_to edit_project_path(id: @project.id), notice: "新規に保存しました"
      end
    else
      set_cache
      flash.now[:notice] = "エラーが発生しました"
      render :edit
    end
  end

  def update
    @project.touch # Blockのみの更新でもUpdateする
    if @project.update(project_params)
      if params[:button] == "issue"
        if publish_project
          redirect_to projects_path, notice: "#{@project.title}を公開しました"
        else
          set_cache
          flash.now[:notice] = "公開に失敗しました"
          render :edit
        end
      else
        redirect_to edit_project_path, notice: "保存しました"
      end
    else
      set_cache
      flash.now[:notice] = "エラーが発生しました"
      render :edit
    end
  end

  def recall
    PublishedProject.find(params[:id]).destroy
    redirect_to edit_project_path, notice: "非公開にしました"
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: "プロジェクトは削除されました。"
  end

  def batch
    @json = Page.project.reorder(order: :DESC).includes(:published_project, :category).map.with_index do |page, order|
      {
        id: page.published_project_id,
        title: page.published_project.title,
        category: page.published_project.category.name,
        overview: page.published_project.overview_jp,
        order: order # 逆順にして渡す
      }
    end.to_json
  end

  def batch_update
    old_orders = Page.project.pluck(:published_project_id, :order).to_h
    last_order = old_orders.count - 1

    projects_params[:projects_attributes].each do |key, project|
      order = last_order - key.to_i # 逆順にして保存
      if order != old_orders[project[:id]]
        page = Page.find_by(published_project_id: project[:id])
        page.update(order: order)
      end
    end

    redirect_to batch_projects_path, notice: "保存しました"
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_props
    if @roles.none?
      preference = Preference.last
      @roles = [@project.roles.new(name: preference.role_default_name, person: preference.role_default_person)]
    end
    @categories = Category.select(:id, :name).order(:display_id).all
    @category_names = Category.pluck(:id, :name).to_h
  end

  # POSTされたparamsをVue用のデータに再整形
  def set_cache
    @cache = { block_new_id: 0, trash: [] }

    # 新規でないidの型が数値
    if params[:project][:roles_attributes]
      @roles = params[:project][:roles_attributes].values.map do |i|
        i[:id] = i [:id].to_i if i[:id].to_i.to_s == i[:id]
        next i
      end
      @roles = @roles.compact
    else
      @roles = []
    end

    # 新規でないidの型が数値で、削除済みはtrashへ分離し、Vue側で復活不可に
    # ファイルアップローダが空の場合{url: null}に
    @cache[:block_new_id] = 0
    if params[:project][:blocks_attributes]
      @blocks = params[:project][:blocks_attributes].values.map do |i|
        if i[:_destroy]
          if i["id"].to_i.to_s == i[:id]
            i[:id] = i[:id].to_i
            i[:type] = nil
            @cache[:trash] << i
          end
          next nil
        else
          i[:id] = (i[:id].to_i.to_s == i[:id]) ? i[:id].to_i : "new_#{@cache[:block_new_id] += 1}"
          i[:file] ||= { url: nil } if i[:type] == "picture"
          next i
        end
      end
      @blocks = @blocks.compact
    else
      @blocks = []
    end

    @cache = @cache.to_json
    set_props
  end

  # プロジェクトを公開テーブルに複製する
  def publish_project
    pub_project = PublishedProject.find_or_initialize_by(id: @project.id)
    pub_project.attributes = @project.attributes
    pub_project.file = @project.file

    pub_project.published_roles = @project.roles.map do |role|
      pub_role = pub_project.published_roles.find_or_initialize_by(id: role.id)
      attr = role.attributes
      attr.delete("project_id")
      pub_role.attributes = attr
      pub_role
    end

    pub_project.published_blocks = @project.blocks.map do |block|
      pub_block = pub_project.published_blocks.find_or_initialize_by(id: block.id)
      attr = block.attributes
      attr.delete("project_id")
      attr[:file] = block.file
      pub_block.attributes = attr
      pub_block
    end

    pub_project.save
  end

  def project_params
    params.require(:project).permit(
      :title, :category_id,
      :date, :color_txt, :color_bg, :color_edge, :file, :file_cache, :is_visible,
      roles_attributes: [
        :display_id, :name, :person, :_destroy, :id
      ],
      blocks_attributes: [
        :display_id, :type, :text_en, :text_jp, :color_txt, :color_bg, :file, :file_cache, :is_visible, :option, :_destroy, :id
      ]
    )
  end

  def projects_params
    params.require(:project).permit(
      projects_attributes: [:id, :order]
    )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_pillar.html.erb
<section class="pillar<%= " pillar-colored" if color_edge != "transparent" %>" style="background-color: <%= color_edge %>;">
  <div class="pillar-roles">
    <% if @roles %>
    <ul class="pillar-roles-list">
      <% @roles.each do |role| %>
      <li class="pillar-roles-item">
        <span class="pillar-roles-parts"><%= role.name %>:</span>
        <span class="pillar-roles-parts"><%= role.person %></span>
      </li>
      <% end %>
      <li class="pillar-roles-item">
        <span class="pillar-roles-parts"><%= @project.date.strftime("%B %Y") %></span>
      </li>
    </ul>
    <% end %>
  </div>
  <div class="pillar-pages">
    <%= link_to edit_project_path(id: @project.id), class: "pillar-pages-link" do %>
      <div class="pillar-pages-item">
        <h2 class="pillar-pages-title"><div>Back to</div>Edit Page</h2>
      </div>
    <% end %>
  </div>
</section>

app/views/projects/batch.html.erb
<% content_for :extend_menu do %>
  <%= link_to projects_path, class: "mdc-list-item mdc-ripple-upgraded" do %>
  <i class="material-icons mdc-list-item__graphic">navigate_before</i><span class="mdc-list-item__text pc-only">BACK</span>
  <% end %>

  <div class="click-event mdc-list-item mdc-ripple-upgraded" data-event="issue">
  <i class="material-icons mdc-list-item__graphic">send</i><span class="mdc-list-item__text pc-only">ISSUE</span>
  </div>
<% end %>

<h1>Issued Projects</h1>
<p class="tip">プロジェクトのページ順を並べ替えます。プロジェクト名をドラッグで並べ替え後、<i class="material-icons">send</i> Issue で保存してください。</p>


<%= form_with(local: true, id: "form_edit", html: {style: "padding-bottom: 1px;"}) do |form| %>
  <div class="island island-filled">
    <%= link_to projects_path do %>
      <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">navigate_before<p class="button-label">一覧に戻る</p></button>
    <% end %>
    <button name="button" type="submit" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded" value="issue">
      <span class="material-icons mdc-fab__icon">send</span>
      <span class="mdc-fab__label">Issue</span>
    </button>
  </div>

  <div class="island">
    <div id="project_list" data-json="<%= @json %>"></div>
  </div>

  <div class="island island-filled">
    <%= link_to projects_path do %>
      <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">navigate_before<p class="button-label">一覧に戻る</p></button>
    <% end %>
    <button name="button" type="submit" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded" value="issue">
      <span class="material-icons mdc-fab__icon">send</span>
      <span class="mdc-fab__label">Issue</span>
    </button>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :extend_menu do %>
  <%= link_to projects_path, class: "mdc-list-item mdc-ripple-upgraded" do %>
  <i class="material-icons mdc-list-item__graphic">navigate_before</i><span class="mdc-list-item__text pc-only">PROJECTS</span>
  <% end %>

  <% if @project.id %>
  <%= link_to show_project_path(@project), class: "mdc-list-item mdc-ripple-upgraded"  do %>
  <i class="material-icons mdc-list-item__graphic">search</i><span class="mdc-list-item__text pc-only">PREVIEW</span>
  <% end %>
  <% end %>

  <div class="click-event mdc-list-item mdc-ripple-upgraded" data-event="submit">
  <i class="material-icons mdc-list-item__graphic">create</i><span class="mdc-list-item__text pc-only">SAVE</span>
  </div>

  <div class="click-event mdc-list-item mdc-ripple-upgraded" data-event="issue">
  <i class="material-icons mdc-list-item__graphic">send</i><span class="mdc-list-item__text pc-only">ISSUE</span>
  </div>

  <% if @is_issued %>
  <%= link_to recall_project_path(@project), class: "mdc-list-item mdc-ripple-upgraded"  do %>
  <i class="material-icons mdc-list-item__graphic">backspace</i><span class="mdc-list-item__text pc-only">RECALL</span>
  <% end %>
  <% end %>
<% end %>

<section class="project-edit-plate">
<%= form_with(model: @project, local: true, id: "form_edit", multipart: true) do |form| %>
  <% if @project.errors.any? %>
  <div class="error-block">
    <h2><%= pluralize(@project.errors.count, "件のエラーがあります") %></h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div id="project_editor" data-project="<%= @project.to_json %>" data-roles="<%= @roles.to_json %>" data-blocks="<%= @blocks.to_json %>" data-category-names="<%= @category_names.to_json %>" data-cache="<%= @cache %>"<% if controller.root? %> data-enable-html="true"<% end %>></div>

  <div class="island island-filled">
    <span class="button-list">
      <%= link_to projects_path do %>
      <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">navigate_before<p class="button-label">一覧に戻る</p>
      </button>
      <% end %>

      <% if @project.id %>
      <%= link_to show_project_path(@project), target: "_new" do %>
      <button name="button" type="button" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded">
        <span class="material-icons mdc-fab__icon">search</span>
        <span class="mdc-fab__label">Preview</span>
      </button>
      <% end %>
      <% end %>

      <button name="button" type="submit" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded">
        <span class="material-icons mdc-fab__icon">create</span>
        <span class="mdc-fab__label">Save</span>
      </button>
      <button name="button" type="submit" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded" value="issue">
        <span class="material-icons mdc-fab__icon">send</span>
        <span class="mdc-fab__label">Issue</span>
      </button>

      <% if @is_issued %>
      <%= link_to recall_project_path(@project) do %>
      <button name="button" type="button" class="mdc-fab mdc-fab--extended mdc-ripple-upgraded">
        <span class="material-icons mdc-fab__icon">backspace</span>
        <span class="mdc-fab__label">Recall</span>
      </button>
      <% end %>
      <% end %>
      <% if @project.id %>
      <button name="button" type="button" class="dialog-open mdc-fab mdc-fab--extended mdc-ripple-upgraded">
        <span class="material-icons mdc-fab__icon">delete_forever</span>
        <span class="mdc-fab__label">Delete</span>
      </button>
      <% end %>
    </span>
    <p class="tip"><i class="material-icons">search</i>PREVIEW: 下書き確認 <i class="material-icons">create</i>SAVE: 内容を保存 <i class="material-icons">send</i>ISSUE: 内容を保存して公開 <i class="material-icons">backspace</i>RECALL: 非公開に変更 <i class="material-icons">delete_forever</i>DELETE: 公開を終了して削除</p>
  </div>

  <div class="island island-filled">
    <p>ファイル合計: <%= number_to_human_size @file_size %></p>
  </div>

<% end #form_with %>
</section>

<% if @project.id %>
  <% content_for :dialog do %>
  <h2 class="mdc-dialog__title">プロジェクトの削除</h2>
  <section class="mdc-dialog__content">
    <p>
      いちど削除すると元には戻せません。<br>
      削除しますか？
    </p>
  </section>
  <footer class="mdc-dialog__actions">
    <button type="button" class="dialog-close mdc-button mdc-button--secondary mdc-ripple-upgraded">キャンセル</button>
    <%= link_to delete_project_path(@project) do %>
    <button type="button" class="mdc-button mdc-ripple-upgraded">削除</button>
    <% end %>
  </footer>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<div class="project-index-header">
  <h1>Projects</h1>
  <%= link_to batch_projects_path do %>
    <button type="button" class="mdc-button mdc-button--icon mdc-button--primary mdc-ripple-upgraded"><i class="material-icons mdc-button__icon">format_list_numbered</i>ページの並べ替え</button>
  <% end %>
</div>
<p class="tip tip-right">公開中のプロジェクトの表示順を変更します。</p>
<p class="tip">仕事や作品のプロジェクトを編集します。プロジェクトをクリックで編集します。プロジェクトの作成・編集をサイトに反映するためには公開する必要があります。<i class="material-icons">flare</i>Unissued が非公開のプロジェクト、<i class="material-icons">landscape</i>Edited が公開後に変更が加えられたプロジェクトです。</p>

<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">

    <div class="mdc-card mdc-layout-grid__cell mdc-layout-grid__cell--span-4 card-new">
      <div class="mdc-card__primary-action mdc-ripple-upgraded">
        <div class="card-surface">
          <%= link_to new_project_path do %>
            <i class="material-icons">add</i>
          <h2>New Project</h2>
          <p class="tip">プロジェクトを新規作成します。</p>

          <% end %>
        </div>
      </div>
    </div>

    <% @projects.each do |project| %>
    <div class="mdc-card mdc-layout-grid__cell mdc-layout-grid__cell--span-4">
      <%= link_to edit_project_path(project) do %>
      <div class="mdc-card__primary-action mdc-ripple-upgraded">
        <div class="mdc-card__media mdc-card__media--16-9"<% if project.file %> style="background-image: url(<%= project.file %>);"<% end %>></div>
        <div class="card-surface" style="border-top: 6px solid <%= project.color_bg %>">
          <h2 class="mdc-typography--headline6">
            <%= project.title %>
          </h2>
          <h3 class="mdc-typography--subtitle2"><%= project.category.name %></h3>
          <div class="mdc-typography--body2">
            <%= project.overview_jp %>
          </div>
          <div class="card-supplement"><%= project.date %></div>
        </div>
      </div>
      <% end %>
      <div class="mdc-card__actions">
        <% if !project.published_project %>
          <i class="material-icons mdc-list-item__graphic">flare</i>Unissued
        <% elsif project.updated_at != project.published_project.updated_at %>
          <i class="material-icons mdc-list-item__graphic">landscape</i>Edited
        <% end %>

        <div class="mdc-card__action-icons">
          <% if @index[project.id] %>
            <%= link_to publish_path(@index[project.id]) do %>
              <button type="button" class="mdc-icon-button mdc-icon-button--colored material-icons">search<p class="button-label">公開中</p></button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>