config/routes.rb
Rails.application.routes.draw do
  scope :sidedoor do
    scope controller: :admins do
      root action: :enter, as: :enter_sidedoor
      post "", action: :unlock
      get :leave, action: :leave, as: :leave_sidedoor
    end

    resources :admins, except: [:show, :destroy]
    get "admins/init", controller: :admins, action: :init, as: :init_admin
    get "admins/:id/delete", controller: :admins, action: :destroy, as: :delete_admin

    resources :projects, only: [:index, :new, :edit, :create, :update]
    scope :projects, controller: :projects do
      get "/batch", action: :batch, as: :batch_projects
      post "/batch", action: :batch_update, as: :batch_update_projects
      get ":id", action: :index
      get ":id/preview", action: :show, as: :show_project
      get ":id/delete", action: :destroy, as: :delete_project
      get ":id/recall", action: :recall, as: :recall_project
    end

    resources :headlines, only: [:index, :new, :edit, :create, :update]
    scope :headlines, controller: :headlines do
      post "sort", action: :sort, as: :sort_headline
      get ":id/delete", action: :destroy, as: :delete_headline
      get "api/:id", action: :api, as: "headlines_api"
    end

    scope :sticky, controller: :stickies do
      root action: :edit, as: :sticky
      post "", action: :update
    end

    scope :contacts, controller: :contacts do
      root action: :index, as: "contacts"
      get "contacts/:id", action: :show, as: "contact"
      get "contacts/:id/resend", action: :resend, as: "resend_contact"
      get "contacts/:id/delete", action: :destroy, as: "delete_contact"
    end

    scope :preference, controller: :preferences do
      root action: :edit, as: :preference
      patch "", action: :update
    end

    get "help/:show", controller: :sidedoor, action: :help_api, as: "help_api"
  end

  root action: :show, controller: "published_projects"
  get "locale/:locale", action: :locale, controller: "published_projects", as: "locale"
  get ":page", action: :show, controller: "published_projects", as: "publish"
  post "contact", action: :contact, controller: "published_projects", as: "send"
end

app/models/published_project.rb
class PublishedProject < ApplicationRecord
  belongs_to :category
  has_many :published_blocks, dependent: :destroy
  accepts_nested_attributes_for :published_blocks, allow_destroy: true
  has_many :published_roles, dependent: :destroy
  accepts_nested_attributes_for :published_roles, allow_destroy: true
  attr_accessor :file
  mount_uploader :file, ImageUploader
  has_many :headlines, dependent: :destroy
  has_one :page, dependent: :destroy

  validates :title, presence: true
  validates :date, presence: true

  after_create :page_create
  after_destroy :file_remove
  after_commit :contents_issue

  # ページ番号順
  scope :index_list, lambda { |display_count|
    includes(:page).order("pages.order DESC").limit(display_count)
  }

  def self.last_issue
    maximum(:updated_at) || Time.news(2018, 6)
  end

  # 本文概要
  def overview
    I18n.locale == :ja ? overview_jp : overview_en
  end

  private

  # 新規公開時にページを追加
  def page_create
    page = Page.find_or_initialize_by(published_project_id: id)
    page.update_attributes(source: :project, order: Page.project.maximum(:order).to_i + 1)
  end
end

app/controllers/published_projects_controller.rb
class PublishedProjectsController < ApplicationController
  layout "portfolio"
  before_action :associate, only: [:show, :locale]
  caches_action :show, if: -> { @cache }, cache_path: ->(c) { create_cache_path(c, @preference) }

  def show
    # カテゴリごとのページ索引
    @index = Page.source_index
    # ページ番号
    @page_no = Page.no(params[:page])

    # 前後ページを含むコンテンツ情報
    pages = Page.around(@page_no)
    return redirect_to root_path if pages.blank?

    case pages[1].source
    when "front"
      @album = Headline.album
      @last_issue = PublishedProject.last_issue.strftime("%B %Y")
      @categories = Category.includes(:published_projects).order(:display_id)
      @menu_deley = 0.3
      @meta_image = @album.first.try(:[], :url)
      render :index
    when "category"
      @category = pages[1].content
      @projects = @category.published_projects.order(date: "DESC")
      @around = { "prev": pages.first, "next": pages.last }.compact
      @meta_title = @category.name
      @meta_image = Headline.first&.file&.url
      render :category
    when "project"
      @project = pages[1].content
      @blocks = @project.published_blocks
      @roles = @project.published_roles
      @around = { "prev": pages.first, "next": pages.last }.compact
      @meta_title = @project.title
      @meta_image = @project.file&.url
      render :show
    end
  end

  # 言語設定を入れ替える
  def locale
    I18n.locale = (params[:locale] == "ja") ? :ja : :en
    cookies[:locale] = I18n.locale

    # flashメッセージをキャッシュしない
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"

    redirect_to root_path, notice: t("messages.locale")
  end

  def contact
    @contact = Contact.new(contact_params)

    begin
      raise if params[:is_valudated]

      # 送信待ち時間
      interval = Time.current - Time.at(params[:accessed_at].to_i)
      minInterval = @contact.body =~ /https?:\/\// ? 60 : 10
      maxInterval = 24 * 60 * 60
      raise ApplicationError::InvalidContactError if interval < minInterval || maxInterval < interval

      # データベース登録
      @contact.save

      # 通知メール送信
      begin
        emails = Admin.where(sendmail: true).pluck(:email)
        ContactMailer.forward(@contact, emails).deliver if emails.present?
      rescue
        raise ApplicationError::NotificationError
      end
      notice = t("messages.contacts.success")
    rescue ApplicationError::InvalidContactError => e
      notice = t("messages.contacts.database_error")
    rescue ActiveRecord::ActiveRecordError => e
      logger.error e
      notice = t("messages.contacts.database_error")
    rescue ApplicationError::NotificationError => e
      logger.error e
      notice = t("messages.contacts.sending_error")
    rescue => e
      logger.error e
      notice = t("messages.contacts.database_error")
    end

    redirect_to root_path, notice: notice
  end

  private

  # キャッシュ判定前
  def associate
    I18n.locale = user_language_ja ? :ja : :en
    @preference = Preference.last
    render_error 500 if @preference.under_construction
    @sticky = Sticky.fetch if params[:page].to_i <= 1
  end

  # ActionCache: Create path
  def create_cache_path(controller, model = nil)
    path = ActionController::Caching::Actions::ActionCachePath.new(controller).path
    path += ":#{I18n.locale}"
    path += ":#{model.updated_at&.strftime('%Y%m%d-%H%M%S')}" if model.present?
    path += ":sticky" if @sticky
    path
  end

  # 日本語を表示可能なアクセスかどうか
  def user_language_ja
    if cookies[:locale]
      cookies[:locale] == "ja"
    else
      language = request.env["HTTP_ACCEPT_LANGUAGE"]
      language && language.casecmp("ja-jp") == 0
    end
  end

  # Storong params: PublishedProject
  def published_project_params
    params.fetch(:published_project, {})
  end

  # Strong params: Contect
  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/helpers/published_projects_helper.rb
module PublishedProjectsHelper
end

app/views/published_projects/_pillar.html.erb
<section class="pillar<%= " pillar-colored" if color_edge != "transparent" %>" style="background-color: <%= color_edge %>;">
  <div class="pillar-roles">
    <% if @roles %>
    <ul class="pillar-roles-list">
      <% @roles.each do |role| %>
      <li class="pillar-roles-item">
        <span class="pillar-roles-parts"><%= role.name %>:</span>
        <span class="pillar-roles-parts"><%= role.person %></span>
      </li>
      <% end %>
      <li class="pillar-roles-item">
        <span class="pillar-roles-parts"><%= @project.date.strftime("%B %Y") %></span>
      </li>  
    </ul>
    <% end %>
  </div>
  <div class="pillar-pages">
  <% @around.each do |key, page| %>
  <% case page.source -%>
  <% when "front" %>
    <%= link_to root_path, class: "pillar-pages-link" do %>
      <div class="pillar-pages-<%= key %> haze">
        <div class="pillar-pages-kind"><%= key.capitalize %> Page</div>
        <h2 class="pillar-pages-title">Front Page</h2>
      </div>
    <% end %>
  <% when "category" %>
    <%= link_to publish_path(@index[:category][page.content.id]), class: "pillar-pages-link" do %>
      <div class="pillar-pages-item pillar-pages-<%= key %> haze">
        <div class="pillar-pages-kind"><%= key.capitalize %> Page</div>
        <h2 class="pillar-pages-title">Category: <%= page.content.name %></h2>
      </div>
    <% end %>
  <% when "project" %>
    <%= link_to publish_path(@index[:project][page.content.id]), class: "pillar-pages-link" do %>
      <div class="pillar-pages-item pillar-pages-<%= key %> haze">
        <div class="pillar-pages-kind"><%= key.capitalize %> Page</div>
        <h2 class="pillar-pages-title"><%= page.content.title %></h2>
        <img src="<%= page.content.file %>" class="pillar-thumbnail<%= " vertical" if page.content.is_portrait %>">
        <p class="pillar-pages-text"><%= page.content.overview %></p>
      </div>
    <% end %>
  <% end %>
  <% end %>
    <%= link_to root_path, class: "pillar-pages-link" do %>
      <div class="pillar-pages-item">
        <h2 class="pillar-pages-title"><div>Back to</div>Front Page</h2>
      </div>
    <% end %>
  </div>
</section>

app/views/published_projects/category.html.erb
<% content_for :main do %>
class="category-plate"
<% end %>
<div>
  <section class="category-main">
    <h1>
      <div class="heading-sub heading-sub-category">Category</div>
      <%= @category.name %>
    </h1>
  </section>

  <div class="project-contents">
    <section class="index-project-group">
    <% if @projects.empty? %>
      <%= t("messages.no_project") %>
    <% else %>
      <% @projects.each do |project| %>
      <%= link_to publish_path(@index[:project][project.id]), class: "index-project" do %>
      <div class="index-thumbnail<%= " vertical" if project.is_portrait %>">
        <div><% if project.file %><img src="<%= project.file %>"><% end %></div>
      </div>
      <div class="index-overview">
        <h3><%= project.title %></h3>
        <div class="card-supplement"><%= project.date.year %></div>
        <p><%= project.overview %></p>
        <p class="index-paginate">p.1</p>
      </div>
      <% end %>
      <% end %>
    <% end %>
    </section>

    <%= render partial: "pillar", locals: {color_edge: @preference.default_color_edge} %>
  </div>
</div>

app/views/published_projects/index.html.erb
<% content_for :main do %>
class="index-plate"
<% end %>
<nav id="index_nav" class="index-nav">
  <a href="https://www.instagram.com/<%= ENV["SNS_INSTAGRAM_NAME"] %>/" target="_blank">
    <svg class="social-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="24" viewBox="0 0 14 14">
      <path fill="#000" d="M13.96 4.11c-.04-.75-.15-1.25-.33-1.7-.18-.46-.42-.85-.81-1.24-.39-.39-.78-.63-1.24-.81-.45-.17-.96-.29-1.7-.33-.74-.02-.98-.03-2.88-.03s-2.14.01-2.89.04-1.25.15-1.7.32c-.46.19-.85.43-1.24.81-.38.39-.62.78-.8 1.24-.17.44-.29.95-.32 1.7-.04.75-.05.99-.05 2.89 0 1.9.01 2.14.04 2.89s.15 1.25.32 1.7c.18.46.42.85.81 1.24.39.39.78.63 1.24.81.45.17.95.29 1.7.33.75.02.99.03 2.89.03 1.9 0 2.14-.01 2.89-.04.74-.03 1.25-.15 1.7-.33.46-.18.85-.42 1.24-.81.39-.39.63-.78.81-1.24.17-.45.29-.95.33-1.7.02-.74.03-.98.03-2.88s-.01-2.14-.04-2.89zm-1.25 5.72c-.03.68-.15 1.05-.24 1.3-.13.33-.28.56-.52.81-.25.25-.48.4-.81.52-.25.1-.62.21-1.3.24-.75.04-.97.05-2.84.05-1.87 0-2.09-.01-2.83-.04-.68-.03-1.05-.15-1.3-.24-.33-.12-.56-.28-.81-.52-.25-.25-.4-.48-.52-.81-.1-.25-.21-.62-.24-1.3-.04-.75-.05-.97-.05-2.84s.01-2.09.04-2.83c.03-.68.15-1.05.24-1.3.13-.33.28-.57.53-.81.25-.24.48-.4.81-.52.25-.1.62-.21 1.3-.24.74-.04.96-.05 2.83-.05s2.09.01 2.83.04c.68.03 1.05.15 1.3.24.33.13.56.28.81.52.25.25.4.48.52.81.1.25.21.62.24 1.3.03.74.04.96.04 2.83s0 2.1-.03 2.84zm-5.71-6.42c-1.99 0-3.59 1.61-3.59 3.59 0 1.98 1.61 3.59 3.59 3.59 1.98 0 3.59-1.61 3.59-3.59 0-1.98-1.61-3.59-3.59-3.59zm0 5.93c-1.29 0-2.34-1.05-2.34-2.34 0-1.29 1.05-2.34 2.34-2.34 1.29 0 2.34 1.05 2.34 2.34 0 1.29-1.05 2.34-2.34 2.34zm3.73-6.91c-.46 0-.84.38-.84.84s.38.84.84.84c.46 0 .84-.38.84-.84s-.38-.84-.84-.84z"/>
    </svg>
  </a>
  <svg id="index_menu_open" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M0 0h24v24H0z" fill="none"/><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/>
  </svg>
</nav>
<aside id="index_menu" class="index-menu">
  <div class="index-menu-close">&times;</div>
  <ul class="index-menu-list">
    <li class="index-menu-list-item"><a href="#top">Top</a></li>
  <% @categories.each_with_index do |category, index| %>
    <li class="index-menu-list-item" style="transition-delay: <%= index * @menu_deley %>s;">
      <a href="#category_<%= category.id %>"><%= category.name %></a>
    </li>
  <% end %>
    <a href="#categories">
      <li class="index-menu-list-item" style="transition-delay: <%= @categories.count * @menu_deley %>s;">Categories</li>
    </a>
    <a href="#contact">
      <li class="index-menu-list-item" style="transition-delay: <%= (@categories.count + 1) * @menu_deley %>s;">Contact</li>
    </a>
    <a href="#about">
      <li class="index-menu-list-item" style="transition-delay: <%= (@categories.count + 2) * @menu_deley %>s;">About</li>
    </a>
    <li class="index-menu-language">
      <%= link_to_if I18n.locale != :en, 'English', locale_path(locale: 'en') %>
      /
      <%= link_to_if I18n.locale != :ja, 'Japanese', locale_path(locale: 'ja') %>
    </li>
  </ul>
</aside>

<section id="top" class="index-main" style="color: #200404; background-color: #ffffff; background-position: initial initial; background-repeat: initial initial;">
  <div class="index-album" id="album" data-album="<%= @album.to_json %>" data-interval="<%= @preference.headline_interval %>"></div>
  <h1>
    <%= image_pack_tag 'media/images/site_logo.png' %>
  </h1>

  <div class="index-date">
    Last Issued <%= @last_issue %>
  </div>
  <div></div>
</section>

<% if @sticky %>
<div class="index-project-group haze">
  <div class="sticky-plate" style="background-image: linear-gradient(120deg, <%= @sticky.color_bg_start %>, <%= @sticky.color_bg_end %>);">
    <%= raw @sticky.html %>
  </div>
</div>
<% end %>

<% @categories.each do |category| %>
<% if category.published_projects.present? && category_page = @index[:category][category.id] %>
<section id="category_<%= category.id %>" class="index-project-group index-project-group-collapsible haze">
  <%= link_to publish_path(category_page), class: "index-category" do %>
    <h2><%= category.name %></h2>
    &gt;&gt; detail p.<%= category_page %>
  <% end %>
  <% category.published_projects.index_list(@preference.projects_display_count).each do |project| %>
    <% if project_page = @index[:project][project.id] %>
    <%= link_to publish_path(project_page), class: "index-project" do %>
      <div class="index-thumbnail">
        <div class="<%= "vertical" if project.is_portrait %>"><% if project.file.thumb %><img src="<%= project.file.thumb %>"><% end %></div>
      </div>
      <div class="index-overview">
        <h3><%= project.title %></h3>
        <div class="card-supplement"><%= project.date.strftime("%B %Y") %></div>
        <p><%= project.overview %></p>
      </div>
    <% end %>
    <% end %>
  <% end %>

  <%= link_to publish_path(@index[:category][category.id]) do %>
  <div class="contrail-link index-omitted">
    <div class="contrail-link-normal">And More</div>
    <div class="contrail-link-hover"><%= category.name %> p.<%= @index[:category][category.id] %></div>
  </div>
  <% end %>
</section>
<% end %>
<% end %>

<section id="categories" class="index-project-group haze">
  <div class="index-category">
    <h2>Categories</h2>
  </div>

  <div class="index-category-list">
  <% @categories.each do |category| %>
    <% if page = @index[:category][category.id] %>
    <div>
      <%= link_to publish_path(page), class: "index-project" do %>
        <h3><%= category.name %><span class="index-paginate">p.<%= page %></span>
        </h3>
        <div class="card-supplement">October 2018</div>
      <% end %>
    </div>
    <% end %>
  <% end %>
  </div>
</section>

<section id="contact" class="index-project-group haze">
  <%= form_with(model: @contact, url: send_path, local: true, id: "contact_form") do |form| %>
    <input type="hidden" name="accessed_at" value="<%= Time.current.to_i %>">
    <div class="index-category">
      <h2>Contact</h2>
    </div>
    <div id="contact_letter" class="contact-letter">
      <div class="contact-letter-front">
        <div class="contact-input">
          <div class="contact-field">
            <label>Name</label><input type="text" name="contact[name]">
          </div>
          <div class="contact-field">
            <label>Email</label><input type="text" class="contact-field" name="contact[email]">
          </div>
          <div class="contact-field">
            <label>Message</label><textarea id="contact_textarea" class="contact-field" name="contact[body]"></textarea>
          </div>
        </div>
        <div class="contact-button">
          <p id="contact_confirm"><%= t("contacts.send") %></p>
        </div>
      </div>
      <div class="contact-letter-back">
        <div class="contact-letter-back-inner">
          <ul id="contact_errors" class="contact-error-list contact-error" data-locale="<%= I18n.locale %>"></ul>
          <p class="contact-letter-back-confirm contact-correct"><%= t("contacts.confirm") %></p>
          <p id="contact_submit" class="contact-letter-back-button contact-correct"><%= t("contacts.yes") %></p>
          <p id="contact_back" class="contact-letter-back-button">
            <span class="contact-correct"><%= t("contacts.no") %></span>
            <span class="contact-error"><%= t("contacts.cancel") %></span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</section>

<section id="about" class="index-colophon haze">
  <div class="imprint">
    <div class="imprint-inner">
      <h3 class="imprint-heading"><%= @preference.owner_name %></h3>
      <p><%= simple_format(h(@preference.profile)) %></p>
    </div>
  </div>

  <p>&copy; 2019- <%= ENV["SITE_OWNER"] %> All Rights Reserved.</p>
  <p>Developed by <%= ENV["SITE_DESIGNER"] %></p>
</section>

app/views/published_projects/show.html.erb
<% content_for :main, %(class="plate-project").html_safe  %>
<section class="facade<%= " facade-colored" if @project.color_bg != "transparent" %>" style="color: <%= @project.color_txt %>; background-color: <%= @project.color_bg %>;">
  <h1 class=""><%= @project.title %></h1>
  <ul class="facade-roles-list">
    <% @roles.each do |role| %>
    <li class="facade-roles-item"><span class="facade-roles-parts"><%= role.name %>:</span>
      <span class="facade-roles-parts"><%= role.person %></span></li>
    <% end %>
    <li class="facade-roles-item"><span class="facade-roles-parts"><%= @project.date.strftime("%B %Y") %></span></li>
  </ul>
  <div class="stone-picture">
    <img class="stone-image-facade<%= " stone-image-facade-portrait" if @project.is_portrait %> haze-image" src="<%= @project.file %>">
  </div>
</section>

<div class="project-contents">
  <section class="stone-list">
  <% @blocks.each do |block| %>
    <div class="stone <%= "stone-colored" if block.color_bg != "transparent" %> stone-<%= block.type %> haze" style="color: <%= block.color_txt %>; background-color: <%= block.color_bg %>;">
    <% case block.type -%>
    <% when "heading" %>
      <h2>
        <div><%= block.text_en %></div>
      </h2>
    <% when "text" %>
      <p><%= block.text %></p>
    <% when "link" %>
      <div class="fountain-link">
        <a class="fountain-link-surface" href="<%= block.option %>" target="_blank">
        <%= block.text %><div class="fountain-link-line"></div>
        </a>
      </div>
    <% when "picture" %>
      <% if block.is_portrait %>
        <div class="stone-image-portrait">
          <div class="stone-image-surface haze-image" style="background-image: url(<%= block.file %>)"></div>
        </div>
      <% else %>
        <div class="stone-image-horizontal">
          <img class="stone-image haze-image" src="<%= block.file %>">
        </div>
      <% end %>
      <% if block.text.present? %>
        <% if block.option.present? %>
          <div class="stone-image-caption">
            <div class="fountain-link">
              <a class="fountain-link-surface" href="<%= block.option %>" target="_blank">
              <%= block.text %><div class="fountain-link-line"></div>
              </a>
            </div>
          </div>
        <% else %>
          <div class="stone-image-caption">
            <span class="stone-image-caption-text"><%= block.text %></span>
          </div>
        <% end %>
      <% end %>
    <% when "html" %>
      <%= raw block.text_en %>
    <% end %>
    </div>
  <% end %>
  </section>

  <%= render partial: "pillar", locals: {color_edge: @project.color_edge} %>
</div>