config/routes.rb
Rails.application.routes.draw do
  scope :sidedoor do
    scope controller: :admins do
      root action: :enter, as: :enter_sidedoor
      post "", action: :unlock
      get :leave, action: :leave, as: :leave_sidedoor
    end

    resources :admins, except: [:show, :destroy]
    get "admins/init", controller: :admins, action: :init, as: :init_admin
    get "admins/:id/delete", controller: :admins, action: :destroy, as: :delete_admin

    resources :projects, only: [:index, :new, :edit, :create, :update]
    scope :projects, controller: :projects do
      get "/batch", action: :batch, as: :batch_projects
      post "/batch", action: :batch_update, as: :batch_update_projects
      get ":id", action: :index
      get ":id/preview", action: :show, as: :show_project
      get ":id/delete", action: :destroy, as: :delete_project
      get ":id/recall", action: :recall, as: :recall_project
    end

    resources :headlines, only: [:index, :new, :edit, :create, :update]
    scope :headlines, controller: :headlines do
      post "sort", action: :sort, as: :sort_headline
      get ":id/delete", action: :destroy, as: :delete_headline
      get "api/:id", action: :api, as: "headlines_api"
    end

    scope :sticky, controller: :stickies do
      root action: :edit, as: :sticky
      post "", action: :update
    end

    scope :contacts, controller: :contacts do
      root action: :index, as: "contacts"
      get "contacts/:id", action: :show, as: "contact"
      get "contacts/:id/resend", action: :resend, as: "resend_contact"
      get "contacts/:id/delete", action: :destroy, as: "delete_contact"
    end

    scope :preference, controller: :preferences do
      root action: :edit, as: :preference
      patch "", action: :update
    end

    get "help/:show", controller: :sidedoor, action: :help_api, as: "help_api"
  end

  root action: :show, controller: "published_projects"
  get "locale/:locale", action: :locale, controller: "published_projects", as: "locale"
  get ":page", action: :show, controller: "published_projects", as: "publish"
  post "contact", action: :contact, controller: "published_projects", as: "send"
end

app/views/layouts/_meta_tags.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<% if @meta_title %>
<meta property="og:type" content="artcle">
<title><%= @meta_title %> - Haruka Shoji</title>
<% else %>
<meta property="og:type" content="website">
<title>Haruka Shoji</title>
<% end %>
<meta name="keywords" content="Textile Design,Installation">
<meta name="description" content="Textile Design / Installation">
<meta property="og:title" content="<%= @meta_title || "Haruka Shoji" %>">
<meta property="og:description" content="Textile Design / Installation">
<meta property="og:url" content="<%= request.url %>">
<meta property="og:image" content="<%= File.join(request.url, @meta_image) if @meta_image %>">
<meta property="og:site_name" content="Haruka Shoji">
<meta property="og:locale" content="<%= I18n.locale === :ja ? "ja_JP" : "en_GB" %>">
<link rel="shortcut icon" href="/favicon.ico">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/android-chrome-512x512.png">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'portfolio', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'portfolio', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="robots" content="noindex">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= ENV["SITE_NAME"] %></title>
    <meta name="robots" content="noindex">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'portfolio', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'portfolio', 'data-turbolinks-track': 'reload', defer: true %>
    <%= render partial: 'layouts/meta_tags' %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body class="<%= "locale-ja" if I18n.locale == :ja %>">
    <main <%= yield :main %>>
      <%= yield %>
      <footer class="paginate paginate-<%= @page_no.even? ? "l" : "r" %>"><%= @page_no %></footer>
    </main>
    <% if notice %>
    <div id="notice" class="notice-plate">
      <%= notice %>
    </div>
    <% end %>
  </body>
</html>

app/views/layouts/sidedoor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'sidedoor', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= @meta_title || controller.controller_name.capitalize %> - <%= ENV["SITE_NAME"] %></title>
    <meta name="robots" content="noindex">
  </head>
  <body class="<%= "show-tip" if @current_admin.show_help %>">
    <aside class="mdc-drawer mdc-drawer--permanent mdc-drawer--persistent">
      <div class="mdc-drawer__header pc-only">
        <h1 class="mdc-drawer__title"><%= controller.controller_name %></h1>
        <h2 class="mdc-drawer__subtitle"><%= ENV["SITE_NAME"] %></h2>
      </div>
      <div class="mdc-drawer__content">
        <nav class="mdc-list">
          <%= link_to root_path, class: "mdc-list-item mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">import_contacts</i>
          <span class="mdc-list-item__text pc-only">サイトを開く</span>
          <% end %>
          <%= link_to headlines_path, class: "mdc-list-item #{"mdc-list-item--selected" if controller.controller_name == "headlines"} mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">gradient</i>
            <span class="mdc-list-item__text pc-only">見出し画像</span>
          <% end %>
          <%= link_to sticky_path, class: "mdc-list-item #{"mdc-list-item--selected" if controller.controller_name == "stickys"} mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">content_paste</i>
            <span class="mdc-list-item__text pc-only">付箋</span>
          <% end %>
          <%= link_to projects_path, class: "mdc-list-item #{"mdc-list-item--selected" if controller.controller_name == "projects"} mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">photo_library</i>
          <span class="mdc-list-item__text pc-only">プロジェクト</span>
          <% end %>
          <%= link_to contacts_path, class: "mdc-list-item #{"mdc-list-item--selected" if controller.controller_name == "contacts"} mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">mail</i>
          <span class="mdc-list-item__text pc-only">メッセージ</span>
          <% end %>
          <%= link_to preference_path, class: "mdc-list-item mdc-ripple-upgraded #{"mdc-list-item--selected" if controller.controller_name == "preferences"}" do %>
          <i class="material-icons mdc-list-item__graphic">settings</i>
          <span class="mdc-list-item__text pc-only">設定</span>
          <% end %>
          <%= link_to leave_sidedoor_path, class: "mdc-list-item mdc-ripple-upgraded" do %>
          <i class="material-icons mdc-list-item__graphic">input</i>
          <span class="mdc-list-item__text pc-only">ログアウト</span>
          <% end %>
        </nav>
        <hr class="mdc-list-divider">
        <h2 class="mdc-list-group__subheader pc-only">Tools</h2>
        <nav class="mdc-list">
          <div class="toggle-tip mdc-list-item mdc-ripple-upgraded">
          <i class="material-icons mdc-list-item__graphic">help</i><span class="mdc-list-item__text pc-only">SHOW HELP</span>
          </div>
          <%= yield :extend_menu %>
        </nav>
      </div>
    </aside>
    <main <%= yield :main %>>
      <%= yield %>

      <div class="mdc-dialog">
        <div class="mdc-dialog__container">
          <div class="mdc-dialog__surface">
            <%= yield :dialog %>
          </div>
        </div>
      </div>
    </main>

    <div id="notice" class="mdc-snackbar mdc-snackbar--align-start">
      <div id="notice_text" class="mdc-snackbar__text"><%= notice.presence %></div>
      <div class="mdc-snackbar__action-wrapper">
        <button type="button" class="mdc-snackbar__action-button"></button>
      </div>
    </div>

    <%= javascript_pack_tag 'sidedoor', 'data-turbolinks-track': 'reload', defer: true %>
  </body>
</html>